### ISSUE TITLE
Reconsider using qt json

### ISSUE THREAD

**Issue by ohmree** [jkbz64/TwitchQt#4]
It seems like the native json support in qt got rewritten to use cbor as a backend, thus eliminating the 127mb limit that was previously cited as a reason for using a 3rd party json lib. 

Would you reconsider using qt's native json impl?  
Not that this matters, I just think one less non-qt dependency is nice.

**Comment by jkbz64** [comment]
I don't mind using new qt's implementation as long as it works.

At that time the qt's json parser didn't seem like good choice mainly for the limit and performance issues, it worked great for small payloads and worked really bad for bigger, but maybe the limit is not that mandatory requirement - IIRC it was required for fetching TwitchEmotes (not official twitch) api, so the support for it can be probably dropped (who knows if someone even uses it)?

The only questionable thing about the cbor backend if I understood the qt's reference correctly is that it was introduced in Qt5.12, and it would break/wouldn't allow for use in olders qt's versions.

I personally don't think having one less non-qt dependency is a big deal since the dependency is header-only, but also I've seen some compiler compatibility issues (probably?) so I'm not against either.

If someone wants to "rewrite" response parsing for every endpoint then feel free, I don't really use the library (and haven't for a lot of time, fixed something month ago because someone reached out to me, I'm also surprised it works and twitch didn't break the api after the 3 years) and don't really want to commit the time.

**Comment by g-fb** [comment]
@ohmree I have done this in my fork https://github.com/jkbz64/TwitchQt, plus other changes.

@jkbz64 if you're ok with the [changes](https://github.com/jkbz64/TwitchQt/compare/master...g-fb:TwitchQt:master) I've done I can pull them here.

**Comment by jkbz64** [comment]
@g-fb 
If you care feel free to pull the changes, I don't really intend to maintain this repo at this point.
I would be fine with just pointing to your fork in the README - assuming you want to continue your fork.

**Comment by g-fb** [comment]
> I don't really intend to maintain this repo at this point.

In that case I'll just continue with my fork.

**Comment by jkbz64** [comment]
> > I don't really intend to maintain this repo at this point.
> 
> In that case I'll just continue with my fork.

Thanks for using and continuing the library :)
